name: Ultimate Backend Scraper (API)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-api-scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Env Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Core Library Load
        run: |
          python -m pip install --upgrade pip
          pip install curl_cffi
          
      - name: RUN Main Fetch API Code
        run: python main.py
          
      - name: Save Excel CSV & DB
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Ultimate-Autowini-Database
          path: |
            *.csv
            *.json
            *.txt
